# Generated by Django 2.0.1 on 2021-02-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics/')),
                ('img2', models.ImageField(upload_to='pics/')),
                ('img3', models.ImageField(upload_to='pics/')),
                ('img4', models.ImageField(upload_to='pics/')),
                ('img5', models.ImageField(upload_to='pics/')),
                ('img6', models.ImageField(upload_to='pics/')),
                ('descricao', models.TextField()),
                ('sugestao', models.TextField()),
            ],
        ),
    ]
